// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5_Gpf1lxt6PYLHmJ4_WJXAG4482kWPzg',
    appId: '1:949612592885:web:9502b4c398f6c5c56dcfbc',
    messagingSenderId: '949612592885',
    projectId: 'pharmko-kenny',
    authDomain: 'pharmko-kenny.firebaseapp.com',
    storageBucket: 'pharmko-kenny.appspot.com',
    measurementId: 'G-1H0PXMSSC5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8uYxKhDR5C12Q0jLKyjeQR4zAg4dV6os',
    appId: '1:949612592885:android:61abaf77b26d53346dcfbc',
    messagingSenderId: '949612592885',
    projectId: 'pharmko-kenny',
    storageBucket: 'pharmko-kenny.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnHI4IVOL-WykHArmUgTJ0eLgJYm_F1VU',
    appId: '1:949612592885:ios:6a49dce31af738616dcfbc',
    messagingSenderId: '949612592885',
    projectId: 'pharmko-kenny',
    storageBucket: 'pharmko-kenny.appspot.com',
    iosBundleId: 'com.pharmko.pharmkoapp',
  );
}
